name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-transaction-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: npm install
        working-directory: services/transaction-service
      - name: Test
        run: npm test
        working-directory: services/transaction-service
      - name: Build
        run: npm run build
        working-directory: services/transaction-service

  test-fraud-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: npm install
        working-directory: services/fraud-service
      - name: Test
        run: npm test
        working-directory: services/fraud-service
      - name: Build
        run: npm run build
        working-directory: services/fraud-service

  test-alert-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: npm install
        working-directory: services/alert-service
      - name: Test
        run: npm test
        working-directory: services/alert-service
      - name: Build
        run: npm run build
        working-directory: services/alert-service

  test-analytics-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: npm install
        working-directory: services/analytics-service
      - name: Test
        run: npm test
        working-directory: services/analytics-service
      - name: Build
        run: npm run build
        working-directory: services/analytics-service

  # Sab pass hone ke baad deploy
  deploy:
    needs: [
      test-transaction-service,
      test-fraud-service,
      test-alert-service,
      test-analytics-service
    ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # sirf main pe deploy
    
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "All tests passed — Deploy here!"